### ISSUE TITLE
Connection refused! Can't specify listening port number

### ISSUE THREAD

**Issue by vladsanchez** [Microsoft/vscode-postgresql#14]
> PostgreSQL: Failed to connect: could not connect to server: Connection refused
> 	Is the server running on host (10.1.1.122) and accepting
> 	TCP/IP connections on port 5433?

**VSCode Version 1.32.3 (1.32.3)**

Please allow for port specification. Not every server defaults to 5433/5432!

Perhaps allow `{host}:{port}` formatting option.

**Comment by garyshell** [comment]
Yes its a really good idea NOT to use the default port, it helps hide the server from hackers and other ne'er do wells.

**Comment by akamath46297** [comment]
@vladsanchez you can provide the port details in the settings file where the connection profiles are maintained as shown below. I agree that it would be good to accept port in the connection creation workflow

![image](https://user-images.githubusercontent.com/30480046/54570222-fd998a00-499a-11e9-904f-c4be561807a9.png)

**Comment by EricPSU** [comment]
You can also provide a port number in the ADVANCED settings within the GUI:

![image](https://user-images.githubusercontent.com/25805189/54704828-e4ffb000-4b11-11e9-88b3-cf7bb5ce47cf.png)

**Comment by JayAndCatchFire** [comment]
It would be nice if there was a way to enter in a custom port number in the "wizard" profile setup.

**Comment by akamath46297** [comment]
@JayAndCatchFire already checked in the code to prompt it during connection creation process. Will be part of next minor upgrade.

**Comment by akamath46297** [comment]
@JayAndCatchFire , @vladsanchez , @garyshell , port is now added as part of connection creation workflow. This is now fixed with [Release 0.2.0](https://github.com/Microsoft/vscode-postgresql/releases/tag/v0.2.0)

**Comment by JayAndCatchFire** [comment]
I can confirm that this is now fixed.  Thank you!

**Comment by akamath46297** [comment]
Thanks for confirming. I am closing the issue

**Comment by mirsahibmovsumov** [comment]
The same issue on Release v0.2.6, I cannot specify port listening port number
