### ISSUE TITLE
Can't Add extension in Mac 

### ISSUE THREAD

**Issue by ndwivedi** [Microsoft/vscode-postgresql#15]
- PGSQL Extension Version:0.1.0
- VSCode Version: ADS 1.5.1
- OS Version: MacOSMojave 10.14.3

Steps to Reproduce:

1. I don't see PostGreSQL as extension when I search but from VS code extension, I downloaded vscode-postgresql-0.1.0-osx.vsix package and installed but when I reload, I get error
<img width="241" alt="ADS Extension" src="https://user-images.githubusercontent.com/9135814/54569339-cfbf4000-49b0-11e9-8135-297669a6b534.png">
<img width="464" alt="Error" src="https://user-images.githubusercontent.com/9135814/54569340-cfbf4000-49b0-11e9-85bb-b03d025941d6.png">

Successfully Installed and working on OS Version: MacOSMojave 10.14.2

**Comment by akamath46297** [comment]
@ndwivedi , just to confirm - Are you saying it worked with MacOSMojave 10.14.2 but not  10.14.3 ?

Also you mentioned VSCode Version: ADS 1.5.1 - Are you trying to install the Azure Data Studio extension or Vscode extension ?

**Comment by ndwivedi** [comment]
Yes it worked in MacOSMojave 10.14.2. As I was not able to find in ADS via extension, I have read an article from Buck Woody that you can install vs code extension, so I tried that. Is there a download page for ADS extension, I can try that too. Thank you so very much for a super fast response. I do appreciate the work ADS team is doing.

**Comment by akamath46297** [comment]
You can find the extension for ADS : https://github.com/Microsoft/azuredatastudio-postgresql/releases. Could you log issues related ADS extension in the https://github.com/Microsoft/azuredatastudio-postgresql repo.

So this issue is for Vscode or ADS ?

**Comment by ndwivedi** [comment]
Thanks Anup,
This is ADS issue. In VS code I am able to configure it properly.
I tried that too. Still getting same error. Will try in some other machines at work, with the same version of OS as mine. Could be something wrong with my machine, since I can’t find extension in extension search.

**Comment by ndwivedi** [comment]
Just wanted to give an update. At work few of my colleagues tried and it works. I also have made some progress, I uninstalled a lot of extensions and now I can see PostGres option in ConnectionType and when I start ADS, on the left bottom corner, the attached message appears and it is stuck at "starting pgsql service". I believe some other extension is still causing some trouble.  
Thank you very much for your help. I will keep de-bugging. 
<img width="203" alt="pgsqlservice" src="https://user-images.githubusercontent.com/9135814/54611017-8e6c7600-4a2c-11e9-8f83-78ce2e26af34.png">

**Comment by ndwivedi** [comment]
Final update. I uninstalled the ADS and deleted everything related to it by going ⁨/Users⁩/⁨XXX/⁨Library⁩ /⁨Application Support⁩/⁨azuredatastudio⁩.
Cleared the trash. Restarted the machine and re-installed the ADS and now I can add Postgres connections successfully. 
Thank you.
