### ISSUE TITLE
Connection to Postgres different than localhost fails on MacOS

### ISSUE THREAD

**Issue by lamuertepeluda** [Microsoft/vscode-postgresql#18]
- PGSQL Extension Version: 0.1.0
- VSCode Version: 1.32.3
- OS Version: MacOS Mojave 10.14.3
- Same happens in Azure Data Studio 1.5.1

Steps to Reproduce:

1. Create a connection different than localhost using hostname:port\dbname
2. Error: `PostgreSQL: Failed to connect: could not translate host name "HOSTNAME:PORT\DBNAME" to address: nodename nor servname provided, or not known`

I don't even get what it means, but in my other client (Postico) I can connect

I also attempted other combinations but no luck. I'd really appreciate some non-localhost example :)

**Comment by lamuertepeluda** [comment]
Ok sorry for opening the issue. I think it was my server not supporting SSL and being on a different port. I made it work in Azure Data Studio like this:

Connection Type: PostgreSQL
Server name: `<your hostname>`
User name: `<your username>`
Password: `<your username>`
[Database name: `<db name>`]

Then press "Advanced"
Port: `<port>`
SSL mode: 'disable'

**Comment by akamath46297** [comment]
@lamuertepeluda , in ADS the main workflow covers basic connection properties, things like port, SSL are in Advanced as you figured out.
In Vscode you should be able to provide these details in the connection profile which is maintained in the user settings json as shown below. Could you try out this and let me know?

![image](https://user-images.githubusercontent.com/30480046/54651844-d06bdb00-4a71-11e9-9382-e0fbd4e9a641.png)

**Comment by lamuertepeluda** [comment]
@akamath46297 great! this solved my issue 😃 

Is it a feature the fact that it requires the user login all the time I make a new connection, even if the user is set in the connection profile in `pgsql.connections`?

![image](https://user-images.githubusercontent.com/2249342/54670217-71e74100-4af3-11e9-8b94-9600004b6b53.png)


Anyway great job guys! I look forward for even cooler features like PostGIS support. I think this is just a very good start

**Comment by akamath46297** [comment]
@lamuertepeluda, the fact that it asks for user name all the time in Vscode is a bug which we will be addressing before next release. We will also add port as an option during create connection workflow.

**Comment by akamath46297** [comment]
@lamuertepeluda, port is now added as part of connection creation workflow. This is now fixed with [Release 0.2.0](https://github.com/Microsoft/vscode-postgresql/releases/tag/v0.2.0)
