### ISSUE TITLE
Manjaro Linux: Platform is not supported

### ISSUE THREAD

**Issue by swratten** [Microsoft/vscode-postgresql#23]
- PGSQL Extension Version: 0.1.0
- VSCode Version: 1.31.1
- OS Version: Manjaro 18.0.3 Illyria - Kernel: x86_64 Linux 4.19.23-1-MANJARO

Steps to Reproduce:

1. Install plugin
2. Try to use any of the plugin commands

![postgresql_vscode](https://user-images.githubusercontent.com/4234090/54726383-d1b71800-4bd7-11e9-9321-c02878f320b7.png)

**Comment by danielpellon** [comment]
I have the same issue when using a command with arch linux.

**Comment by boras1988** [comment]
Also Arch, same problem.
Any idea how to debug the extension? Are there any logs? What is the exact reason for the platform to be considered not supported?

**Comment by danielpellon** [comment]
I was able to add support for Arch Linux and will be submitting a pull request shortly.

@swratten could you tell me the output of `cat /etc/os-release ` from Manjaro? Then I could also include it in the pull request.

**Comment by danielpellon** [comment]
@lukipro The supported linux distributions are hard-coded in the extension and arch was not included, for your question about debugging the extension, [this guide](https://github.com/Microsoft/vscode-postgresql/wiki/How-to-Contribute) with instructions is provided in the readme.

Why was it chosen to hard-code the supported linux distributions?

**Comment by akamath46297** [comment]
@lukipro , thanks for the PR. We will take a look into this. We wanted to make sure we enable the extension for Linux distributions that we have test for. And what you see in the code is the list of tested Linux distributions.

**Comment by akamath46297** [comment]
@lukipro , @danielpellon and @swratten could you guys try this out with latest [Release 0.2.0](https://github.com/Microsoft/vscode-postgresql/releases/tag/v0.2.0)

**Comment by danielpellon** [comment]
@akamath46297 Can confirm the release is working for me.

**Comment by akamath46297** [comment]
Closing this issue.
