### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by mblataric** [Microsoft/vscode-postgresql#28]
- PGSQL Extension Version: 0.1.0
- VSCode Version: 1.32.3
- OS Version: macOS 10.14.4

In extension description one of the features listed is:
 - Write queries with Intellisense

However, I could not found a way to get Intellisense working. 
Am I missing something?

**Comment by akamath46297** [comment]
@mblataric , this is a know issue with this version of VSCODE. We will have to update our language client. We will provide a fix soon. Sorry for the inconvenience

**Comment by akamath46297** [comment]
@mblataric , this is now fixed with [Release 0.2.0](https://github.com/Microsoft/vscode-postgresql/releases/tag/v0.2.0)
