### ISSUE TITLE
Error: command 'vscode.previewHtml' not found -  MacOS

### ISSUE THREAD

**Issue by resistorsoftware** [Microsoft/vscode-postgresql#31]
- PGSQL Extension Version: 0.1.0
- VSCode Version: Version 1.33.0 (1.33.0)
- OS Version: macos 10.14.4

Steps to Reproduce:

1. Install extension
2. shift-command P, new query
3. provide localhost, database name, user, password
4. write simple query
5. execute query

This was working fine until I updated MacOS. Now this extension and VSCode do not work at all. Any attempt to run a query results in the terminal error message  *Error: command 'vscode.previewHtml' not found* and nothing else. No query is ever run.

Looking in the logs, it is clear the extension does run:

10:24:31 AM] Started query execution for document "untitled:Untitled-1"
[10:24:31 AM] Finished query execution for document "untitled:Untitled-1"

However no data is retrieved or displayed.

**Comment by akamath46297** [comment]
@resistorsoftware , thanks for reporting. With VSCODE 1.33.0 vscode.previewHtml is deprecated. We have published the new release with this fix and bunch of other fixes here https://github.com/Microsoft/vscode-postgresql/releases/tag/v0.2.0

**Comment by akamath46297** [comment]
This is fixed with 0.2.0 release
