### ISSUE TITLE
Error: command 'vscode.previewHtml' not found

### ISSUE THREAD

**Issue by matthiasdaues** [Microsoft/vscode-postgresql#32]
- PGSQL Extension Version: 0.1.0
- VSCode Version: 1.33.0
- OS Version: windows 7

Steps to Reproduce:

1. type a select statement: select count(*) from connection.table
2. get error message: "Error: command 'vscode.previewHtml' not found"

**Comment by akamath46297** [comment]
@matthiasdaues thanks for reporting. With VSCODE 1.33.0 vscode.previewHtml is deprecated. We have published the new release with this fix and bunch of other fixes here https://github.com/Microsoft/vscode-postgresql/releases/tag/v0.2.0

**Comment by akamath46297** [comment]
This is fixed now with latest #33
