### ISSUE TITLE
why not to contribute to other extensions that already exists?

### ISSUE THREAD

**Issue by mtxr** [Microsoft/vscode-postgresql#43]
Hi,

Please, don't get me wrong, but we currently have lots of extensions providing database connections for many RDBMS like MySQL, PostgreSQL, SQL Server, Oracle..

Why not support and encourage the developers to keep with all those already kind of successful project instead of creating a new extension?

I one of those developers, and particularly I don't get the point of creating a new extension every time instead of contributing. I'm not talking about Microsoft only, but we have dozen of extensions being created every time.

I'm a really fan of VSCode, in fact I've already submitted PRs for docs and the core code, but I really don't get this point.

I'm just looking for an explanation, because I prefer to contribute to this project instead of keep trying to grow a project that would be probably forgotten just because here we have Microsoft's name. I just want a good tool to work with and I really don't mind to contribute, just want a direction.

Sincerely,
M.

**Comment by ronychatterjee** [comment]
Hi Matheus,

You raise a very valid point. While I completely understand and hear your concern I would like to provide a little background from our side. 

We have been working on the support for PostgreSQL extension in Azure Data Studio for a while when we initially got started on the SQL offering. We wanted to understand what it would take for us to support multi databases in Azure Data Studio and what are the platform needs which would enable us to support so.  We want to provide users with the flexibility of the choice of tools they would prefer to use and the code has been entirely open source for the community to contribute back into. Azure Data Studio being completely based on top of VS Code it provided us an opportunity to contribute to the VS Code ecosystem as well. We are also working not only on the database experience but potentially making sure it is easy for users to discover their Azure Resources and launch experiences like the Notebook with the context of the connection from the Object Explorer.

We really would love to see the community taking this forward and expand into multiple database offerings.

Please let me know if you have any questions.

Thanks,

Rony

**Comment by mtxr** [comment]
@ronychatterjee Thanks for reaching me back. 

Actually It does make a lot of sense. As said, I just want to have great tools to work with, and I like where it's going.

I hope you are willing to receive contributions, would be a pleasure to contribute.

Regards,

Matheus.
