### ISSUE TITLE
Encoding error when result set contains non-ascii character

### ISSUE THREAD

**Issue by korompaiistvan** [microsoft/vscode-postgresql#59]
- PGSQL Extension Version: 0.2.0
- VSCode Version: 1.37.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Run a query in which the result set contains a non-ascii character. e.g. 'ä'
The following query is enough to produce the error: `select 'ä'`
2. Receive the following error:
```
	Started executing query at Line 1
	
	Commands completed successfully 
	
	Unhandled exception while executing query: 'ascii' codec can't encode character '\xe4' in position 8: ordinal not in range(128) 
	
	Total execution time: 00:00:00
```

**Comment by swjain23** [comment]
@korompaiistvan - This issue has been fixed. Can you check on your end?

**Comment by cconrad** [comment]
I just installed the extension and also experience this issue. Any help would be appreciated. I tried changing the client encoding with the SQL command "SET CLIENT_ENCODING TO 'Unicode';", but it did not help.
